Support mercurial

diff --git a/zsh/functions/prompt_apure_setup b/zsh/functions/prompt_apure_setup
--- a/zsh/functions/prompt_apure_setup
+++ b/zsh/functions/prompt_apure_setup
@@ -9,11 +9,11 @@
 # and agnoster
 # https://gist.github.com/agnoster/3712874
 # MIT License
+#
+# Read the ZSH vcs_info docs here:
+# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
 
 # For my own and others sanity
-# git:
-# %b => current branch
-# %a => current action (rebase/merge)
 # prompt:
 # %F => color dict
 # %f => reset color
@@ -33,11 +33,12 @@
 #
 # Prompt rendering
 #
-BRANCH="\ue0a0"
+BRANCH="\ue0a0" # Branch icon supplied by Powerline fonts
+MERCURY="\u263F" # Unicode mercury icon
 PRIMARY_BG=black
 PRIMARY_FG=white
 
-# Wite a colorful segment
+# Write a colorful segment
 # Takes two arguments, background and foreground. Both can be omitted,
 # rendering default background/foreground.
 prompt_apure_color() {
@@ -55,20 +56,6 @@ prompt_apure_user() {
   fi
 }
 
-# Git: branch/detached head
-prompt_apure_git() {
-  local color ref
-  ref="$vcs_info_msg_0_"
-  if [[ -n "$ref" ]]; then
-    if [[ "${ref/.../}" == "$ref" ]]; then
-      ref="$ref"
-    else
-      ref="${ref/.../}"
-    fi
-    print -P "$BRANCH $ref"
-  fi
-}
-
 # Python virtualenv
 prompt_apure_virtualenv() {
   if [[ -n "$VIRTUAL_ENV" ]]; then
@@ -77,27 +64,69 @@ prompt_apure_virtualenv() {
   fi
 }
 
-prompt_apure_render() {
-  [[ -n $vcs_info_msg_1_ ]] && prompt_apure_proj="$vcs_info_msg_1_" || prompt_apure_proj="%2~"
-  [[ -n $vcs_info_msg_2_ ]] && prompt_apure_subdir="./${vcs_info_msg_2_}"
-  [[  "$prompt_apure_subdir" = "./." ]] && prompt_apure_subdir="" || prompt_apure_subdir="$prompt_apure_subdir "
-
-  local last
-  if [[ $KEYMAP = 'vicmd' ]]; then
-    last="▏"
+# Renders "❱❱ <arg1> ❱❭"
+# with an indicator for the current vim mode.
+# Takes 1 arg: the text to put in the arrow.
+prompt_apure_arrow() {
+  # Signal VIM command or insert mode
+  local mode_indicator
+  if [[ $KEYMAP == 'vicmd' ]]; then
+    mode_indicator="▏"
   else
-    last="❭"
+    mode_indicator="❭"
   fi
 
-  prompt_apure_line2="%(?.%F{173}.%F{red})❱❱ ${prompt_apure_proj} ❱${last}%{%f%b%k%} "
+  # Color red if previous command exited with an error code
+  local color
+  [[ prompt_apure_exit_code -eq 0 ]] && color="%F{173}" || color="%F{red}"
 
-  if [[ -n $vcs_info_msg_1_ ]]; then
-PROMPT="
-$(prompt_apure_virtualenv)${prompt_apure_subdir}$(prompt_apure_git)
-$prompt_apure_line2"
+  print -P "${color}❱❱ $1 ❱${mode_indicator}%{%f%b%k%}"
+}
+
+# Renders local path within a project
+prompt_apure_proj_path() {
+  local subdir="./$prompt_apure_vcs_info[subdir]"
+  # Ignore subdir at root of project
+  [[ "$subdir" == "./." ]] && subdir=""
+  # Append trailing space to non-empty subdir
+  [[ -n "$subdir" ]] && subdir="$subdir "
+  print -P "$subdir"
+}
+
+# Renders current branch or bookmark
+prompt_apure_branch() {
+  local vcs=$prompt_apure_vcs_info[vcs]
+  local branch icon
+  if [[ $vcs == "git" ]]; then
+    branch="${prompt_apure_vcs_info[branch]/.../}"
+    icon=$BRANCH
+  elif [[ $vcs == "hg" ]]; then
+    branch="${prompt_apure_vcs_info[misc]}"
+    icon=$MERCURY
+  fi
+
+  if [[ -n "$branch" ]]; then
+    print -P "$icon $branch"
+  fi
+}
+
+prompt_apure_render() {
+  local vcs=$prompt_apure_vcs_info[vcs] # Ex: "git", "hg"
+  local proj=$prompt_apure_vcs_info[base-name] # Project root folder name
+  local action=$prompt_apure_vcs_info[action] # Rebase, merge, etc
+  local dir_suffix="%2~" # ZSH prompt syntax for last to dirs of cwd
+
+  if [[ -n $vcs ]]; then
+    line1="$(prompt_apure_virtualenv)$(prompt_apure_proj_path)$(prompt_apure_branch)${action}"
+    if [[ -n "$line1" ]]; then
+line1="
+${line1}"
+    fi
+PROMPT="$line1
+$(prompt_apure_arrow $proj) "
   else
 PROMPT="
-$prompt_apure_line2"
+$(prompt_apure_arrow $dir_suffix) "
   fi
 }
 
@@ -118,6 +147,8 @@ $prompt_apure_line2"
 #
 
 prompt_apure_precmd() {
+  prompt_apure_exit_code=$? # Record previous exit code before its clobbered
+  prompt_apure_vcs_info=() # Clear stale info
 	vcs_info
   prompt_apure_render
 }
@@ -147,15 +178,18 @@ prompt_apure_setup() {
 	add-zsh-hook precmd prompt_apure_precmd
 	add-zsh-hook preexec prompt_apure_preexec
 
-	zstyle ':vcs_info:*' enable git
+	zstyle ':vcs_info:*' enable hg git
 	zstyle ':vcs_info:*' use-simple true
-	# only export two msg variables from vcs_info
-	zstyle ':vcs_info:*' max-exports 3
-	# vcs_info_msg_0_ = ' %b' (for branch)
-	# vcs_info_msg_1_ = '%r' git repo name (%r)
-	# vcs_info_msg_2_ = '%S' path within repo
-	zstyle ':vcs_info:git*' formats '%b' '%r' '%S'
-	zstyle ':vcs_info:git*' actionformats '%b|%a' '%r' '%S'
+	# only export one msg variables from vcs_info, to invoke our set-message hook
+	zstyle ':vcs_info:*' max-exports 1
+  # get-bookmarks requires get-revision
+  zstyle ':vcs_info:hg*:*' get-revision true
+  zstyle ':vcs_info:hg*:*' get-bookmarks true
+  zstyle ':vcs_info:hg*+gen-hg-bookmark-string:*' hooks hg-bookmark-string
+  zstyle ':vcs_info:*+set-message:*' hooks set-message
+
+  # Debug
+  # zstyle ':vcs_info:*+*:*' debug true
 
 	# if the user has not registered a custom zle widget for clear-screen,
 	# override the builtin one so that the preprompt is displayed correctly when
@@ -169,6 +203,40 @@ prompt_apure_setup() {
 
 	# show username if root, with username in white
 	[[ $UID -eq 0 ]] && prompt_apure_username=' %F{white}%n%f'
+}
+
+#
+# vcs_info Hooks
+#
+
+# Stash all VCS info in a global associative array
+# to use when we render the prompt.
+# Alternative to format + vcs_info_msg_N_ that
+# See the set-message hook_com keys for available data:
+# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Hooks-in-vcs_005finfo
+typeset -g -A prompt_apure_vcs_info # global associative array
+function +vi-set-message() {
+  # set -A prompt_apure_vcs_info "${(@kv)hook_com}"
+  # Copy keys and values from hook_com to prompt_apure_vcs_info
+  prompt_apure_vcs_info=( "${(@kv)hook_com}" )
+  # Uncomment the loop below to dump out all values for debugging
+  # for k in ${(k)hook_com}; do
+  #   echo "$k -> $hook_com[$k]"
+  # done
+}
+
+# Customize to remove trailing * from active bookmark,
+# only show active bookmark
+function +vi-hg-bookmark-string() {
+	if [[ -n "${hook_com[hg-active-bookmark]}" ]]; then
+		hook_com[hg-bookmark-string]="${hook_com[hg-active-bookmark]}"
+
+		# And to signal, that we want to use the string we just generated,
+		# set the special variable `ret' to something other than the default
+		# zero:
+		ret=1
+		return 0
+	fi
 }
 
 #
